import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    fontFamily: 'arial,Gotham,Futura',
  },
  barraSuperior: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#004aad',
    height: 120,
    paddingHorizontal: 15,
  },
  barraPesquisa: {
    flex: 1,
    height: 40,
    backgroundColor: 'white',
    borderRadius: 20,
    paddingHorizontal: 10,
    color: '#333',
    marginHorizontal: 10,
    marginTop: 35,
  },
  logo: {
    height: 60,
    width: 50,
    marginTop: 35,
  },
  menuLateral: {
    position: 'absolute',
    top: 130,
    left: 0,
    width: width * 0.7,
    backgroundColor: '#0047AB',
    height: '100%',
    paddingTop: 20,
    paddingHorizontal: 10,
    zIndex: 2,
  },
  itemMenu: {
    color: 'white',
    fontSize: 16,
    paddingVertical: 10,
  },
  sobreposicao: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  conteudo: {
    flex: 1,
    backgroundColor: '#fff',
  },
  bolinha: {
    borderRadius: 50,
    width: 80,
    height: 80,
    backgroundColor: '#f1f1f1',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },

  imagemBolinha: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  secaoProdutos: {
    marginVertical: 10,
    
  },
  
  textsecao:{
   alignItems:'center', 
  },
  
  tituloSecaoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  tituloSecao: {
    fontSize: 17,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  verTodos: {
    fontSize: 16,
    color: '#555',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  scrollHorizontal: {
    paddingVertical: 10,
  },
  gridProdutos: {
    flexDirection: 'row',
    paddingVertical: 30,
  },
  itemProduto: {
    margin: 10,
    width: 180,
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    overflow: 'hidden',
  },
  imagemProduto: {
    width: 190,
    height: 150,
    resizeMode: 'cover',
  },
  infoProduto: {
    padding: 5,
  },
  nomeProduto: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  descricaoProduto: {
    fontSize: 11,
    marginTop: 10,
  },
  precoProduto: {
    marginVertical: 7,
    fontSize: 16,
    color: '#004aad',
    fontWeight: 'bold',
  },
  botaoAdicionar: {
    marginTop: 25, 
    backgroundColor: '#004aad',
    paddingVertical: 5,
    paddingHorizontal: 30,
    borderRadius: 5,
    alignItems: 'center',
    padding: 5,
    color:'white',
  },
  textoBotaoAdicionar: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  inputQuantidade: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    width: '100%',
    padding: 10,
    marginBottom: 15,
    textAlign: 'center',
  },
  textoBotaoConfirmar: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  textoBotaoCancelar: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  banner: {
    width: 450,
    height: 270,
    resizeMode: 'stretch',
    borderRadius: 10,
  },
  categoriasContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 30,
  },
  
  categoriaContainer: {
    alignItems: 'center',
    flex: 1,
  },
  
  textoCategoria: {
    fontSize: 14,
    color: '#333',
  },
  textoBotaoQuantidade: {
    fontSize: 16,
    width: 28,
    height: 28,
    backgroundColor: '#009B',
    borderRadius: 100,
    borderWidth: 1,
    textAlign: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontWeight: 'bold',
  },
  quantidadeContainer: {
    backgroundColor: '#cdcdcd',
    height: 50,
    width: 100,
    justifyContent: 'space-around',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#000', 
    marginBottom: 10,
    marginTop: 10,
  },
  quantidadeTexto: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  secaoEssenciasBebidasCombos: {
    marginVertical: 10,
  },
  tituloSecaoEssencias: {
    fontSize: 17,
    fontWeight: 'bold',
    paddingHorizontal: 20,
    marginVertical: 10,
  },
  secaoEssenciasBebidasCombosContainer: {
    flexDirection: 'row',
    paddingVertical: 10,
    justifyContent: 'space-around',
  },
  itemSecaoEssenciasBebidasCombos: {
    width: 150,
    backgroundColor: 'white',
    borderRadius: 10,
    marginRight: 17,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1,
    elevation: 2,
    alignItems: 'center',
  },
  imagemSecaoEssenciasBebidasCombos: {
    width: 100,
    height: 100,
    borderRadius: 10,
  },
  infoSecaoEssenciasBebidasCombos: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  nomeSecaoEssenciasBebidasCombos: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  descricaoSecaoEssenciasBebidasCombos: {
    fontSize: 12,
    textAlign: 'center',
    color:'white',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '100%', 
    marginTop: 5,
  },
  botaomodaladicionar:{
    borderColor: '#000', 
    borderWidth: 1,
    borderRadius: 15,
    padding: 10,
    width: 85,
    backgroundColor: '#00008B', 
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 13,
  },
  botaomodalcancelar:{
    borderColor: '#000', 
    borderWidth: 1,
    borderRadius: 15,
    padding: 10,
    width: 85,
    backgroundColor: '#DC143C', 
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontWeight: 'bold',
    paddingLeft: 12,
  },
  bannerContainer: {
  width: 360,
  height: 180,
  marginLeft: 43,
  marginBottom: 20, 
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#f2f2f2',
},
bannerImagem: {
  width: 369,
  height: 180,
  resizeMode: 'cover',
  borderRadius: 5,
},
bannerContainerNarguile:{
  width: '100%',
  height: 180,
  resizeMode: 'cover',
  borderRadius: 5,
},
bannerImagemNarguile:{
  width: '100%',
  height: 180,
  resizeMode: 'cover',  
  borderRadius: 5,
},
});